# Generated by Django 4.0 on 2022-07-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageReply',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='replyDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
