# Generated by Django 4.0 on 2022-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_femaleuser_gallery_femaleuser_tempgallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleuser',
            name='cellPhone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='cellPhone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
