# Generated by Django 4.0 on 2022-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_femaleuser_cellphone_alter_maleuser_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleuser',
            name='lockedId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maleuser',
            name='lockedId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='matchShowLimit',
            field=models.IntegerField(null=True),
        ),
    ]
