# Generated by Django 4.0 on 2022-10-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_adminlog_xuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleuser',
            name='reqLock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maleuser',
            name='reqLock',
            field=models.IntegerField(null=True),
        ),
    ]
