# Generated by Django 4.0 on 2022-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_femaleuser_reqlock_maleuser_reqlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleuser',
            name='album',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='cv',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='gallery',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='govIssuedId',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='photo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='signature',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='tempGallery',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='album',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='cv',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='gallery',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='govIssuedId',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='photo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='signature',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='tempGallery',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
