# Generated by Django 4.0 on 2023-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_alter_femaleuser_album_alter_femaleuser_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleuser',
            name='health',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='personalWebsite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='preReligiousBrief',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='userPass',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='health',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='personalWebsite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='preReligiousBrief',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='userPass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
