# Generated by Django 5.0.6 on 2024-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_alter_matchmaking_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmaking',
            name='femaleId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchmaking',
            name='maleId',
            field=models.IntegerField(null=True),
        ),
    ]
