# Generated by Django 4.0 on 2022-05-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_post_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='param1',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='param2',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='param3',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='param4',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='param5',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
