# Generated by Django 4.0 on 2022-07-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rename_posttitle_post_pagetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleuser',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maleuser',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
