# Generated by Django 4.0 on 2022-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_femaleuser_cumatchid_maleuser_cumatchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('adminId', models.IntegerField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('userType', models.IntegerField(null=True)),
                ('action', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('actionTime', models.DateTimeField()),
            ],
        ),
    ]
