# Generated by Django 5.0.6 on 2024-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_matchmaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmaking',
            name='percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
