# Generated by Django 4.0 on 2022-07-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_message_messagereply_message_replydatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleuser',
            name='gallery',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='femaleuser',
            name='tempGallery',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='maleuser',
            name='gallery',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='maleuser',
            name='tempGallery',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='cellPhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='homePhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='femaleuser',
            name='workPhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='cellPhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='homePhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maleuser',
            name='workPhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
