# Generated by Django 4.0 on 2022-09-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_adminlog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='note',
            field=models.IntegerField(null=True),
        ),
    ]
