# Generated by Django 4.0 on 2024-05-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_alter_femaleuser_health_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMaking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.IntegerField(default=0, null=True)),
                ('statusMale', models.IntegerField(choices=[(0, 'Normal'), (1, 'ReqSent'), (2, 'ReqPending'), (3, 'ReqAccepted'), (4, 'ReqRejected'), (5, 'Lock_req'), (6, 'Locked')], default=0)),
                ('femaleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.femaleuser')),
                ('maleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.maleuser')),
            ],
        ),
    ]
