# Generated by Django 4.0 on 2024-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_matchmaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmaking',
            name='statusMale',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'ReqSentbyMale'), (2, 'ReqSentbyFemale'), (3, 'ReqAccepted'), (4, 'ReqRejected'), (5, 'Lock_req'), (6, 'Locked')], default=0),
        ),
    ]
