# Generated by Django 4.0 on 2024-05-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_alter_matchmaking_statusmale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchmaking',
            old_name='statusMale',
            new_name='statusReq',
        ),
    ]
