# Generated by Django 5.0.6 on 2024-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_rename_statusmale_matchmaking_statusreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmaking',
            name='statusReq',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'ReqSentByMale'), (2, 'ReqSentByFemale'), (3, 'ReqAccepted'), (4, 'ReqRejected'), (5, 'LockReqByMale'), (6, 'LockReqByFemale'), (7, 'Locked')], default=0),
        ),
    ]
